### ISSUE TITLE
Nodejs version requirement

### ISSUE THREAD

**Issue by kawhicurry** [robocin/WebSoccerMonitor#19]
I've checked my nodejs-v10* and it broken. So I update it to v16.14.0 and it works well.

How about add nodejs version requirement in `README.md`?

**Comment by mtfbs** [comment]
I've added the nodejs version requirement in `README.md` (d56756bf6408a3044657b5099de666708caaaa1a) and updated the node version in `packaje.json` (fca27a075fa09d31b9b24131a895ceb0806ebc8f)

Thanks!
